- extras/multisigs.json
- extras/signers.json
Setup Multisig for handling $ARB from the DAO grant.
Requires a majority of signers to KYC with Arbitrum (but not otherwise dox).
KYCed signers will be named as kycsigner1 - kycsigner3.  
I certify that these are 3 different people all of whom are connected to Balancer.  The Arbitrum KYC process will do the same.
> Arbitrum DAO KYC

- extras/arbitrum.json
Adds vester addresses for each maxi on arbitrum. This is where auraBAL will be sent respectively for Q4 2023.
> arbitrum_vesting_contract_addresses

- .gitmodules
- transform-deployments.py
probing ci workflows, ignore pr for now
> feat: deterministicly sort `path.glob`

- config/core_pools_blacklist.json
…n all data sources.
https://app.balancer.fi/#/arbitrum/pool/0x36bf227d6bac96e2ab1ebb5492ecec69c691943f000200000000000000000316
> Blacklist old wstETH/ETH gauge that is unkilled but doesn't show up in all data sources.

- extras/signers.json
Please do not merge until has has been returned to the gas station.
@SHAKOTN mind sending the gas back to `0x7fb8f5D04b521B6880158819E69538655AABD5c4`
It would also be cool if you could send any L2 gas back to the LM multisig and/or an active deployer (xeonus) on the relevent chains and include tx links here.
> chore: Move shak's deployer wallet to emeritus after being removed from gas station.

- bal_addresses/graphql/core/last_join_exit.gql
- bal_addresses/pools_gauges.py
This is important for protocol fees because this si the last time that accrued fees are registered as such in the subgraph and sent to the collector.
> feat: add last join/exit query. (tagged 0.9.1pre1)

- .github/dependabot.yaml
enabling dependabot for updates on github actions packages, [just like in the multisig ops repo](https://github.com/BalancerMaxis/multisig-ops/blob/main/.github/dependabot.yaml)
> ci: enable dependabot updates for workflows

- extras/signers.json
This wallet will need gas on new chains to deploy the protocol.
> Add Juani's deployer wallet

- extras/arbitrum.json
A second $ARB injector to be used by the origin protocol for their injections that have nothing to do with our STIP funds.
> Add origin ARB injector

- extras/polygon.json
@Zen-Maxi is working on programmning it.  Upkeep already configured here and managed by the omnichain safe.  Polygon LM msig is owner but must still accept ownership:
https://automation.chain.link/polygon/53026144304098248732404862724891564093021434679646217417021318899523816795791
> add wmatic rewards injector on polygon for USDC program

- bal_addresses/requirements.txt
- gen_subgraph_urls.py
- outputs/subgraph_urls.json
- setup.py
this is after using the latest bal_tools, and thus upgrading to the sdk config as a source for the urls
bumps the package itself to v0.9.6
> chore: gen subgraph urls

- extras/signers.json
this was already reviewed in #359 but put in the wrong file (`outputs/`)
> chore: add payees to extras

- extras/arbitrum.json
For use on GHO Arbitrum Guages until there  gauge governance is complete.
> add aave arb injector.

- gen_pools_and_gauges.py
last run failed to retrieve pools and gauges for ethereum and gnosis, but the error was caught and the ci workflow continued (https://github.com/BalancerMaxis/bal_addresses/actions/runs/10252037228/job/28361482279)
```
mainnet
Error using core subgraph for mainnet, skipping: 429 Client Error: Too Many Requests for url: https://api.studio.thegraph.com/query/75376/balancer-v2/version/latest
polygon
arbitrum
optimism
gnosis
Error using core subgraph for gnosis, skipping: 504 Server Error: Gateway Timeout for url: https://api.studio.thegraph.com/query/75376/balancer-gnosis-chain-v2/version/latest
zkevm
goerli
Error using core subgraph for goerli, skipping: 410 Client Error: Gone for url: https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-goerli-v2
Error using gauge subgraph for …
```
> fix: only run for prod chains and raise on errors

- extras/mainnet.json
Should be setup in chainlink and ownership transfered before this PR is merged.
> Add mainnet BAL injector.

- .github/workflows/generate_addressbooks.yaml
- bal_addresses/requirements.txt
- gen_subgraph_urls.py
- setup.py
also include the subgraph generation script in the cron workflow
> chore: bump bal tools version in order to use new subgraph urls

- extras/arbitrum.json
Per recent request from Gyroscope this safe 0xDB9F47800bA9CDd9f99815Bc02dD0Aa47AbffE88 will distribute ARB to Gyro gauges claimed from AAVE rehype pools.
Per Stakewise this safe: 0x2685C0e39EEAAd383fB71ec3F493991d532A87ae will distribute SWISE token 0x4026AFfABd9032bCC87Fa05C02F088905f3dC09B on Arbitrum, starting with one pool.
https://app.balancer.fi/#/arbitrum/pool/0x42f7cfc38dd1583ffda2e4f047f4f6fa06cefc7c000000000000000000000553
> Adding-Stakewise-&-Gyro_Arbitrum-Distributors

- bal_addresses/requirements.txt
- setup.py
https://github.com/BalancerMaxis/bal_tools/releases/tag/v0.1.12
needed for v2 allocator
> bump bal_tools 0.1.12

- extras/arbitrum.json
- extras/mainnet.json
adding addrs used in: https://github.com/BalancerMaxis/multisig-ops/pull/1488/files#diff-effdea1184a8b4481c4beff6194ed518e3dfd296ef8548635c8f27deef3ca38e
[arbi HH bal briber](https://arbiscan.io/address/0xA8214b4Fb98936Ed45463956aFD24a862cC86Dc1)
[arbi paladin distributor](https://arbiscan.io/address/0xB5757D5D93a26EaA3Bc6b0b25cb2364bE8d5b90E)
[mainnet paladin distributor](https://etherscan.io/address/0x1F7b4Bf0CD21c1FBC4F1d995BA0608fDfC992aF4)
> add paladin distributor and HH bal briber

- extras/mainnet.json
As per request for Figue in the Paladin Partner chat:
Chainlink Automation: https://automation.chain.link/mainnet/1162209358248010138892593534629421720784058705808131142117019239632224091812
Still owned by Tritiums deployer,  but can be taken over by omnichain safe with an acceptOwnership.
> Add mainnet NET injector for Paladin/Nektar.

- gen_mono_addressbook.py
- outputs/addressbook.json
This approach takes a minimal change approach, whereby in the resulting addresbook the v2/v3 directory name is ignored/not present. It assumes that all v3 deployments will start with v3- and we can filter on this.  This approach invovles no braking changes to anything that currently runs, but also provides the least structure/information about what belongs to what.
> fix:  minimal change - handle tasks with v2/v3 in path name in deployments directory sturcture

- config/core_pools_blacklist.json
- uses custom rate provider for tight range and does not meet core pool criteria and should therefore be blacklisted
> chore: blacklist base eclp

- bal_addresses/requirements.txt
- setup.py
https://github.com/BalancerMaxis/bal_tools/releases/tag/v0.1.18
> chore: bump bal tools to v.0.1.18

- extras/arbitrum.json
- extras/avalanche.json
- extras/base.json
- extras/mainnet.json
- move some (but not all) of v1 injectors to a deprecated subcategory
- keep some token injectors as they might be used in the future (e.g. ARB STIP injector)
> chore: deprecate old v1 injectors

- gen_pools_and_gauges.py
started getting collisions: https://github.com/BalancerMaxis/bal_addresses/actions/runs/15462136981/job/43525693377
```
Generating pools and gauges for gnosis...
Found duplicate symbols!
address                        symbol
120  0x25e1f4fc31a627979e0940ef59c0158aa84f8c0f  circlesBackingLBP-s-CRC-25e1
213  0x25e17285e08749b5f9e32ac8137f29cfc71edc61  circlesBackingLBP-s-CRC-25e1
```
> fix: ignore circles backing pools

- extras/mainnet.json
- add mainnet GYD label, injector is managed by Gyroscope
- Owner: 0xbA53D5bF49362Ec2907B12DB3468Bb5Be16F5704 (Gyro safe)
> Chore: add Gyroscope managed GYD injector on mainnet

- extras/signers.json
- move all inactive signers and payees to emeritus category
- keep zen in emergency signer group, remove from others
> chore: clean-up signer set

- .github/workflows/generate_addressbooks.yaml
- .github/workflows/generate_core_pools.yaml
- .github/workflows/generate_permissions.yaml
github-actions[bot] cannot trigger other workflows as a security measure. needs either pat (personal token) or github app
this implements the latter
see https://github.com/organizations/BalancerMaxis/settings/installations/85217153
> ci: use github app

- .github/workflows/generate_addressbooks.yaml
Potential fix for [https://github.com/BalancerMaxis/bal_addresses/security/code-scanning/12](https://github.com/BalancerMaxis/bal_addresses/security/code-scanning/12)
To fix the problem, we should add a top-level `permissions:` key to the workflow YAML or, if finer control is needed, at the job level. In this case, top-level permissions are simpler since there is only one job.  
Examining the workflow's actions:
- It checks out code using a generated GitHub App token (not `GITHUB_TOKEN`), but actions like `create-pull-request` and merging PRs will require write access to pull requests.
- The minimal necessary permissions appear to be:
- `contents: read` (to pull source code, although this is done with a token)
- `pull-requests: write` for creating/merging pull requests
Therefore, adding …
> Potential fix for code scanning alert no. 12: Workflow does not contain permissions

- extras/signers.json
- New emergency signer for juani is 0xDA07B188daE2ee63B2eC61Ee4cdB9673C03d2293 See https://etherscan.io/verifySig/281558
- all emergency safe tx's to swap owner initiated
> chore: switch Juani Emergency signer
