- extras/signers.json
> add oz defender relayer as EOA

- extras/multisigs.json
- added grants and three rocks treasury wallet addresses (based on BIP specs)
> Upgrade Multisigs with new SP wallets

- .github/workflows/test.yml
- Makefile
- README.md
- bal_addresses/addresses.py
- bal_addresses/exceptions.py
- bal_addresses/requirements-dev.txt
- bal_addresses/requirements.txt
- tests/test_addresses.py
1. Implement deployments support using Munch library that provides first class object access to the data
2. Add simple tests
3. Setup CI with tests
4. Update docs for how to use new feature
Fixes #63
> Deployments fetch

- bal_addresses/addresses.py
- bal_addresses/permissions.py
- extras/arbitrum.json
- extras/func_desc_by_name.json
- extras/mainnet.json
- extras/polygon.json
- pyproject.toml
- setup.py
Was failing to work as did not install Munch by default.
> Get rid of dotmap and add dependancy info.

- extras/mainnet.json
https://forum.balancer.fi/t/bip-395-delegate-aave-stkaave-to-tokenlogic/5042
> Add tokenlogic aave delegate

- extras/multisigs.json
See #125 
Check signers on:
https://app.safe.global/settings/setup?safe=arb1:0x5891b90CE909d4c3540d640d2BdAAF3fD5157EAD
> add maxi ops safe on arbitrum

- extras/base.json
> fix maxi keepers in base.

- extras/avalanche.json
- extras/base.json
- extras/mainnet.json
https://mimic-fi.notion.site/Balancer-Fee-Collector-v3-Test-Base-Avalanche-and-Mainnet-instructions-89bda03acb7b4cf09b2bb2794eb0fa31#89b9190d21c240409f6eabca86c8778c
> add mimic smartvault v2

- transform-deployments.py
minor, but again introduces more consistency and reproducability for the resulting `addressbook.json`
> feat: more sorting of directory lists

- extras/multisigs.json
Controlled by the maxi signer set + gosuto
> add fee recycling multisig on all chains

- extras/arbitrum.json
Injector is managed/owned by Danny from foxify: https://t.me/DannyFoxify
> Add Fox reward injector to injector list

- extras/multisigs.json
as per specs in bip draft [here](https://forum.balancer.fi/t/bip-xxx-business-development-funding-proposal-q1-2024-and-retroactive-q4-2023-funding/5481) and tritiums comment [here](https://github.com/BalancerMaxis/multisig-ops/pull/703#issuecomment-1868017774)
> chore: add bizdev msig and add opco label

- extras/signers.json
This addressis being paid via the DAO Multisig.
https://forum.balancer.fi/t/bip-525-business-development-funding-proposal-q1-2024-and-retroactive-q4-2023-funding/5481/4
> Add Json as a contributor.

- extras/multisigs.json
based on franz's comments here: https://forum.balancer.fi/t/bip-xxx-linear-pool-hack-restituion/5541/3?u=gosuto
> fix: update beets treasuries

- .github/workflows/generate_addressbooks.yaml
- .github/workflows/generate_permissions.yaml
As requested by Xeonus to better align with gauge adds.
> move cron day to wednesday

- extras/signers.json
Adding newly registered hot-wallet from Xeonus: 0x735Fddb3e475e5f7A61Ef674c72a7eDe82D1f493
> Upgrade Maxi Deployers

- bal_addresses/subgraph.py
- gen_subgraph_urls.py
- outputs/subgraph_urls.json
- tests/test_subgraph.py
closes #239 
- adds data verification on `chain` parameter when initiating `Subgraph`
- adds script that can be run manually to dump all subgraph urls to json
> feat: verify chain parameter for `Subgraph` and dump subgraph urls to json

- extras/signers.json
> Add a 4th KYC signer.

- extras/mainnet.json
Vault Factory and Config contract
> Add Myso baseline contracts

- extras/chains.json
- extras/fantom.json
- extras/multisigs.json
- gen_pools_and_gauges.py
- tests/conftest.py
trying to get the sim working for https://github.com/BalancerMaxis/multisig-ops/pull/916
> feat: add fantom chain

- generate_current_permissions.py
current workflow gets stuck on http error 410 for infura goerli endpoint (resource no longer available)
> fix: remove goerli, infura endpoint has been removed

- extras/signers.json
Add entires for both gas wallets and payee wallets for Jalbrekt and Hyferion.  Asked @Hyferion  to separate the 2 wallets/submit a new one.
> Update new contributors

- extras/arbitrum.json
Accept Ownership tx: https://app.onchainden.com/safes/arb1:0xc38c5f97B34E175FFd35407fc91a937300E33860/transactions/0xcf68af2c024a9184455ec8ca14f07f6e215bbebeb6f512afe2dea0870276a5fa?nid=322247
> Add Arbitrum USDC injector.

- bal_addresses/__init__.py
- bal_addresses/utils.py
and make both is_address and to_checksum_address easier to import.
> fix: is_address 

- bal_addresses/addresses.py
- tests/test_addresses.py
See https://github.com/BalancerMaxis/bal_addresses/actions/runs/8946507813
> fix: Don't break if a chain vanishes (goerli)

- extras/mainnet.json
Distributes direct incentives to Balancer Gauges.
> Add Paladin Questboard

- .github/workflows/generate_core_pools.yaml
- extras/chains.json
- gen_core_pools.py
closes https://github.com/BalancerMaxis/multisig-ops/issues/980
> fix: only generate core pools for production chains

- extras/signers.json
https://forum.balancer.fi/t/bip-367-update-addresses-for-emergency-multisigs/4988
> Update emergency dao signers as per BIP-367

- extras/multisigs.json
Still needs signers to be changes (is 2/7).  Do not merge until this is completed.
> Add EmergencyDAO multisig on new chains.

- bal_addresses/addresses.py
> fix: do not reinstantiate dict every iteration

- extras/arbitrum.json
> Add Gyro Foundation Multisig on arbitrum - rewards distributor

- extras/mainnet.json
pertains to https://github.com/BalancerMaxis/multisig-ops/pull/1026
> chore: add safe ecosystem addresses

- extras/mainnet.json
confirm on etherscan or https://docs.aura.finance/developers/deployed-addresses
> chore: add aura vested escrow

- outputs/addressbook.json
- add Maxi target wallets for mainnet payments to contributors-payees field
- add additional external service field for discord-antiscam-bot target wallet
> feat: add payees set on mainnet

- extras/arbitrum.json
- extras/optimism.json
https://docs.redacted.finance/resources/contract-addresses/hidden-hand-contracts
> Add hidden hand L2 addresses that we may use.

- extras/signers.json
related to https://github.com/BalancerMaxis/multisig-ops/pull/1128
> chore: update emergency dao signers

- extras/mainnet.json
v1 can be verfied here https://app.safe.global/settings/modules?safe=eth:0x0EFcCBb9E2C09Ea29551879bd9Da32362b32fc89 and v2 in their proposal: https://forum.balancer.fi/t/bip-xxx-roles-v2-migration-new-treasury-permissions/5742
> chore: add kpk roles modules

- extras/mainnet.json
https://bridge.gnosischain.com/bridge-explorer/bridges
> Add mainnet gnosis omnibridge:

- bal_addresses/requirements.txt
- extras/chains.json
- setup.py
also bumps bal_tools to latest
> chore: add mode and fraxtal to prod

- extras/mainnet.json
> chore: add hh ops msig

- extras/signers.json
via https://forum.balancer.fi/t/bip-xxx-update-the-optimism-fees-lm-multisig-to-include-beethoven-x-signers/5910
> chore: add some beethoven signers

- extras/mainnet.json
via https://forum.balancer.fi/t/bip-xxx-update-dao-multisig-signers-and-backup-signers/5909
> chore: add nanexcool payee

- extras/signers.json
as per https://forum.balancer.fi/t/bip-681-update-dao-multisig-signers-and-backup-signers/
still need confirmation from anna and hubert
> chore: add backup signers

- extras/arbitrum.json
> add beefy boost contracts for lido incentives.

- extras/signers.json
> chore: add kpk balancer eoa

- extras/mainnet.json
can be confirmed here https://forum.gnosis.io/t/candidate-deployment-of-cow-vesting-contracts-for-those-who-locked-gno/4208
> chore: add cow airdrop merkle distributor

- .github/workflows/generate_addressbooks.yaml
- .github/workflows/generate_core_pools.yaml
- .github/workflows/generate_permissions.yaml
> ci: rename cron prs to avoid confusion

- extras/mainnet.json
- extras/multisigs.json
ref: https://forum.balancer.fi/t/bip-578-engage-wonderland-as-a-service-provider/5659#eth-address-to-receive-funds-10
> fix: move wonderland msig to payees

- extras/signers.json
- add omnification labs
- add drpc USDC funding address
dRPC -> see comms:
> feat: update external payees

- extras/mainnet.json
- extras/signers.json
cantina can be verified here https://app.aave.com/governance/v3/proposal/?proposalId=97
> chore: add cantina and move payee msigs

- extras/mainnet.json
- extras/polygon.json
See for more context:
https://github.com/BalancerMaxis/multisig-ops/pull/1433
Sources:
https://github.com/security-alliance/safe-harbor/blob/main/documents/agreement.pdf
It's on page 9 or 1.1 c
or:
https://github.com/security-alliance/safe-harbor/blob/main/documents/deployment.txt
> add safe_harbor registry

- extras/mode.json
First pass at adding important MODE addresses: Token, ve8020 staking contract, and single staking contract.
> veMODE-Governance-Addresses-1

- extras/avalanche.json
0xeE17b1A400b009b7d05C659a5F17d77E45dfc161
> Gyroscope-Qi-reward-Multisig

- extras/mainnet.json
Per recent interactions with sdBAL payroll.
> Adding-sdBAL-Contracts

- extras/arbitrum.json
diff between the contracts: https://www.diffchecker.com/F3yNfVYK/
> chore: paladin redeployed their arb1 quest board

- extras/optimism.json
some form of confirmation here: https://github.com/AngleProtocol/merkl-contracts/blob/a7020975374c95d15c48791e7f77acd1065f3eb6/deploy/mtw.ts#L13 or on etherscan: https://optimistic.etherscan.io/address/0x8BB4C975Ff3c250e0ceEA271728547f3802B36Fd
> chore: add angle's distribution creator

- extras/zkevm.json
ref: https://mimic-fi.notion.site/Balancer-Fee-Collector-V3-Test-zkEVM-6483c52170a845de8c9509fe64b07855
related to https://github.com/BalancerMaxis/multisig-ops/pull/1522
> chore: add mimic on zkevm

- extras/multisigs.json
> Add Sepolia Emergency DAO safe for testing.

- gen_addresses.py
- gen_core_pools.py
- gen_current_permissions.py
- gen_mono_addressbook.py
- gen_pools_and_gauges.py
- gen_subgraph_urls.py
if json files dont have this prettier will keep trying to add this
> style: end json file dumps with a newline

- extras/mainnet.json
Initial settings: 100k GEAR max per injection, anyone can upkeep, omnichain is owner
> Add GEAR injector on mainnet

- .gitignore
- extras/mainnet.json
pending https://github.com/BalancerMaxis/multisig-ops/issues/1533
> chore: add sdbal vesting factory

- extras/fantom.json
- extras/sonic.json
related to https://github.com/BalancerMaxis/multisig-ops/pull/1664
> chore: add beets on sonic

- extras/multisigs.json
afaik this should not break any scripts
> chore: deprecate msigs and remove duplicates

- .gitignore
- extras/mainnet.json
ref: https://github.com/BalancerMaxis/bal-cow-token-swap?tab=readme-ov-file#deployment
> chore: add bal cow otc contract

- extras/mainnet.json
see usage in https://github.com/BalancerMaxis/multisig-ops/pull/1575
refs:
- https://docs.morpho.org/addresses/
- https://app.merkl.xyz/status
> chore: add morpho and angle contracts

- extras/arbitrum.json
- extras/avalanche.json
- extras/base.json
- extras/fraxtal.json
- extras/gnosis.json
- extras/mainnet.json
- extras/mode.json
- extras/optimism.json
- extras/polygon.json
- extras/zkevm.json
- safe module in helpers category for each chain
- identical address on each network
> feat: add hypernative cspv6 pause safe module

- extras/arbitrum.json
Keeper
https://automation.chain.link/arbitrum/28637510773110834689099351575236032236076784772836048727562419435387475972016
> InjectorV2 on Arbitrum

- extras/gnosis.json
ref: https://reports.karpatkey.com/gnosis?month=1&year=2025&currency=USD
> chore: add gnosis dao treasury

- extras/mainnet.json
Based on the creation of vesters from the txn history here. https://etherscan.io/address/0x032007EC766D7fD0061d20aC9130894878433bd0#internaltx
> sdBAL Vester additions

- bal_addresses/requirements.txt
- setup.py
> feat: move to using main branch of bal tools

- .github/workflows/generate_core_pools.yaml
- extras/mainnet.json
https://github.com/sparkdotfi/spark-user-actions
> chore: add spark's usds psm wrapper

- extras/gnosis.json
https://gnosisscan.io/token/0xaf204776c7245bf4147c2612bf6e5972ee483701
> chore: add gno:sdai

- extras/gnosis.json
https://gnosisscan.io/token/0x2a22f9c3b484c3629090feed35f17ff8f88f76f0
> chore: add gno:usdc.e

- extras/base.json
As per Paladin / Rings request:
> Add Paladin Quest Board on Base

- extras/avalanche.json
as per tg message:
note: contract is unverified!
> chore: add mimic fee burner

- extras/mainnet.json
https://forum.balancer.fi/t/bip-xxx-add-rezerve-rzr-as-a-reward-token-for-the-rzr-wsteth-gauge/6652
> chore: add rezerve deployer

- extras/mainnet.json
using in: https://github.com/BalancerMaxis/protocol_fee_allocator_v2/pull/191
https://docs.paladin.vote/deployed-contracts/mainnet#quest-v2_1
> add paladin aura questboard

- extras/mainnet.json
used in https://github.com/BalancerMaxis/protocol_fee_allocator_v2/pull/225
> add v1 stakedao vote market addr
